name: ventura_hr
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^3.2.2+1
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_native_splash: ^1.1.8+4
  flutter_login: ^1.1.0
  equatable: ^2.0.2
  connectivity_plus: ^1.0.1
  asuka: ^2.0.0-nullsafety.2
  analyzer: ^2.4.0
  dartz: ^0.10.0-nullsafety.1
  string_validator: ^0.3.0
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  firebase_auth_platform_interface: ^5.0.0
  simple_animations: ^3.1.1
  convex_bottom_bar: ^3.0.0
  json_serializable: ^5.0.2
  cloud_firestore: ^2.2.2
  flutter_staggered_animations: ^1.0.0
  clipboard: ^0.1.3
  firebase_storage: ^10.0.1
  url_launcher: ^6.0.9
  filter_list: ^1.0.0
  flutter_slidable: ^1.1.0
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+2
  build_runner: ^2.1.4
  modular_codegen: ^3.0.0-nullsafety.0
  flutter_modular_test: ^1.0.1
  mockito: ^5.0.16
flutter:
  uses-material-design: true
  assets:
  - assets/
